import React from "react";

function Icon(props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      enableBackground="new 0 0 465.691 465.691"
      viewBox="0 0 465.69 465.69"
    >
      <defs>
        <filter
          id="filter1711"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1727"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1743"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1759"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1775"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1791"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1807"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1823"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1839"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1855"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1871"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1887"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1903"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1919"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1935"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1951"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1967"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1983"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter1999"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
        <filter
          id="filter2015"
          width="1"
          height="1"
          x="0"
          y="0"
          colorInterpolationFilters="sRGB"
        >
          <feComposite
            in2="SourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="SourceGraphic"
            k2="1"
            operator="in"
            result="fbSourceGraphic"
          ></feComposite>
          <feColorMatrix
            in="fbSourceGraphic"
            result="fbSourceGraphicAlpha"
            values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
          ></feColorMatrix>
          <feComposite
            in="fbSourceGraphic"
            in2="fbSourceGraphic"
            k2="1"
            operator="arithmetic"
            result="composite1"
          ></feComposite>
          <feColorMatrix
            in="composite1"
            result="colormatrix1"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feFlood floodColor={props.color} result="flood1"></feFlood>
          <feBlend
            in="flood1"
            in2="colormatrix1"
            mode="multiply"
            result="blend1"
          ></feBlend>
          <feBlend in2="blend1" mode="screen" result="blend2"></feBlend>
          <feColorMatrix
            in="blend2"
            result="colormatrix2"
            type="saturate"
            values="1"
          ></feColorMatrix>
          <feComposite
            in="colormatrix2"
            in2="fbSourceGraphic"
            k2="1"
            operator="in"
            result="composite2"
          ></feComposite>
        </filter>
      </defs>
      <path
        fill="#EF7954"
        d="M316.61 126.25H80.19V29.552h205.77c16.926 0 30.648 13.721 30.648 30.648v66.05z"
        filter="url(#filter2015)"
      ></path>
      <path
        fill="#ccc"
        d="M379.12 119.02H43.34v57.105h335.78c15.769 0 28.552-12.783 28.552-28.552.001-15.769-12.783-28.553-28.552-28.553z"
        filter="url(#filter1999)"
      ></path>
      <path
        fill="#D3674A"
        d="M358.33 147c0 15.772-12.78 28.552-28.552 28.552H95.648c15.772 0 28.552-12.78 28.552-28.552s-12.78-28.552-28.552-28.552h234.13c15.773-.001 28.553 12.779 28.553 28.552z"
        filter="url(#filter1983)"
      ></path>
      <path
        fill="#ccc"
        d="M439.42 339.44c0 11.695-4.408 22.374-11.649 30.46-8.36 9.342-20.512 15.224-34.035 15.224H93.366v-91.368h300.37c25.229 0 45.684 20.455 45.684 45.684z"
        filter="url(#filter1967)"
      ></path>
      <path
        fill="#EF7954"
        d="M406.3 339.44c0 25.229-20.455 45.684-45.684 45.684 0 0-190.73-20.455-190.73-45.684s-20.455-45.684-45.684-45.684h236.42c25.229 0 45.684 20.455 45.684 45.684z"
        filter="url(#filter1951)"
      ></path>
      <path
        fill="#B3B3B3"
        d="M190.83 369.9l-20.941-30.46-.001.351c-.126 16.734-14.019 30.109-30.753 30.109H93.369v15.224h300.37c13.523 0 25.674-5.882 34.035-15.224h-236.95z"
        filter="url(#filter1935)"
      ></path>
      <path
        fill="#ccc"
        d="M391.74 234.09c0 19.827-9.674 37.392-24.555 48.242-9.845 7.184-21.985 11.421-35.108 11.421h-272.4v-119.34h272.4c12.769 0 24.601 4.009 34.297 10.839a60.025 60.025 0 0117.942 19.987c4.729 8.554 7.424 18.387 7.424 28.849z"
        filter="url(#filter1919)"
      ></path>
      <path
        fill="#B3B3B3"
        d="M367.18 282.34c-9.845 7.184-21.985 11.421-35.108 11.421h-272.4V282.34h307.51z"
        filter="url(#filter1903)"
      ></path>
      <path
        fill="#B3B3B3"
        d="M384.32 205.24H52.22v-19.987h314.16a60.017 60.017 0 0117.943 19.987z"
        filter="url(#filter1887)"
      ></path>
      <path
        fill="#EF7954"
        d="M345.22 234.09c0 19.827-9.674 37.404-24.567 48.242-9.845 7.184-21.985 11.421-35.097 11.421h-183.33c13.111 0 25.252-4.237 35.097-11.421 14.893-10.839 24.567-28.415 24.567-48.242 0-10.462-2.695-20.295-7.424-28.849a59.826 59.826 0 00-17.954-19.987 59.374 59.374 0 00-34.286-10.839h183.33a59.374 59.374 0 0134.286 10.839 59.826 59.826 0 0117.954 19.987c4.729 8.554 7.424 18.387 7.424 28.849z"
        filter="url(#filter1871)"
      ></path>
      <path
        fill="#B3B3B3"
        d="M43.339 128.72H199.239V185.825H43.339z"
        filter="url(#filter1855)"
      ></path>
      <path
        fill="#999"
        d="M71.892 147.57c0 15.772-12.78 28.552-28.552 28.552s-28.552-12.78-28.552-28.552 12.78-28.552 28.552-28.552 28.552 12.779 28.552 28.552z"
        filter="url(#filter1839)"
      ></path>
      <path
        fill="#ccc"
        d="M437.14 128.15H101.36v57.105h335.78c15.769 0 28.552-12.783 28.552-28.552.001-15.77-12.783-28.553-28.552-28.553z"
        filter="url(#filter1823)"
      ></path>
      <path
        fill="#999"
        d="M129.91 156.71c0 15.772-12.78 28.552-28.552 28.552s-28.552-12.78-28.552-28.552 12.78-28.552 28.552-28.552 28.552 12.779 28.552 28.552z"
        filter="url(#filter1807)"
      ></path>
      <path
        fill="#999"
        d="M119.34 234.09c0 32.95-26.714 59.663-59.663 59.663-18.81 0-35.588-8.703-46.518-22.294C4.925 261.226.002 248.229.002 234.09a59.412 59.412 0 0113.157-37.381c10.93-13.591 27.707-22.294 46.518-22.294 32.949 0 59.663 26.714 59.663 59.675z"
        filter="url(#filter1791)"
      ></path>
      <g fill="gray" filter="url(#filter1775)">
        <path d="M114.15 339.44c0 9.5-6.39 17.53-15.11 19.99-1.8.52-3.7.79-5.67.79-11.48 0-20.78-9.31-20.78-20.78 0-11.48 9.3-20.78 20.78-20.78 1.97 0 3.87.27 5.67.79 8.72 2.461 15.11 10.481 15.11 19.99zM56.327 147.56c0 5.15-2.99 9.59-7.32 11.7-1.72.83-3.64 1.29-5.67 1.29-7.17 0-12.98-5.81-12.98-12.99 0-7.17 5.81-12.98 12.98-12.98 2.03 0 3.95.46 5.67 1.3 4.33 2.1 7.32 6.541 7.32 11.68zM86.807 234.08c0 13.04-9.2 23.94-21.47 26.54-1.83.4-3.73.6-5.67.6-14.99 0-27.14-12.15-27.14-27.14s12.15-27.14 27.14-27.14c1.94 0 3.84.2 5.67.6 12.27 2.6 21.47 13.5 21.47 26.54zM114.35 156.7c0 5.14-2.98 9.58-7.31 11.69-1.72.83-3.64 1.3-5.68 1.3-7.17 0-12.98-5.82-12.98-12.99s5.81-12.99 12.98-12.99c2.04 0 3.96.47 5.68 1.3 4.33 2.11 7.31 6.55 7.31 11.69z"></path>
      </g>
      <g fill="#666" filter="url(#filter1759)">
        <path d="M114.15 339.44c0 9.5-6.39 17.53-15.11 19.99-8.72-2.46-15.12-10.48-15.12-19.99 0-9.52 6.4-17.53 15.12-19.99 8.72 2.461 15.11 10.481 15.11 19.99zM56.327 147.56c0 5.15-2.99 9.59-7.32 11.7-4.33-2.11-7.32-6.55-7.32-11.7 0-5.14 2.99-9.58 7.32-11.68 4.33 2.1 7.32 6.541 7.32 11.68zM86.807 234.08c0 13.04-9.2 23.94-21.47 26.54-12.27-2.6-21.47-13.5-21.47-26.54s9.2-23.94 21.47-26.54c12.27 2.6 21.47 13.5 21.47 26.54zM114.35 156.7c0 5.14-2.98 9.58-7.31 11.69-4.34-2.1-7.33-6.55-7.33-11.69s2.99-9.59 7.33-11.69c4.33 2.11 7.31 6.55 7.31 11.69z"></path>
      </g>
      <path
        fill="#D3674A"
        d="M337.8 205.24H154.47a59.826 59.826 0 00-17.954-19.987h183.33A59.837 59.837 0 01337.8 205.24z"
        filter="url(#filter1743)"
      ></path>
      <path
        fill="#D3674A"
        d="M320.66 282.34c-9.845 7.184-21.985 11.421-35.097 11.421h-183.33c13.111 0 25.252-4.237 35.097-11.421h183.33z"
        filter="url(#filter1727)"
      ></path>
      <path
        fill="#EF7954"
        d="M406.3 436.14H206.27c-20.096 0-36.387-16.291-36.387-36.387v-60.311h236.42v96.698z"
        filter="url(#filter1711)"
      ></path>
    </svg>
  );
}

export default Icon;
